### ISSUE TITLE
A question about the model training

### ISSUE THREAD

**Issue by dmhyun** [MANGA-UOFA/NAUS#1]
Hi, thanks for sharing the great work! I have a question about the model training.

I think that NAUS is trained for each length such as 8, 10, or 13 to control the summary length. I wonder what happens if NAUS is trained for multiple lengths at the same time. This approach can enable NAUS to handle various lengths compared to the current approach (training the model for each length independently). Is there any reason to train NAUS for each length independently instead of training it for multiple lengths at the same time?

**Comment by puyuanliu** [comment]
Sorry for the late reply, I was not monitoring this repo. 
Thank you for the comment! We did consider training NAUS with a mixture of summaries of different lengths. However, we were not able to investigate this setting rigorously due to the time constraint.
It would be really nice if you can share some results on this (if you are trying/planning to try this setting).

**Comment by dmhyun** [comment]
I got it. Thanks for the information!
